version: "3.9"

services:
  db:
    image: mysql:5.7
    networks:
      - web_network
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    ports:
      - 3306:3306
    restart: always
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    networks:
      - web_network
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 7770:80
    restart: always

  nodejs:
    depends_on:
      - db
    build: .
    image: nodejs_docker:1.0  
    container_name: nodejs-siteinfo
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    ports:
      - 3333:3000
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    networks:
      - web_network
    restart: always

networks:
  web_network:
    name: node-docker
    driver: bridge